include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - one_member_abstracts
    - slash_for_doc_comments
    - unnecessary_brace_in_string_interps

analyzer:
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: info
